// Generated by tools/generate_ua_parser_tables.mjs from ua-parser-js v2.0.9.
// Do not edit by hand.

pub const Field = enum { name, version, major, type, vendor, model, architecture };
pub const Function = enum { lowerize, trim, str_mapper, normalize_email_name, whatsapp_os };
pub const PropKind = enum { capture, static, static_null, func, replace, replace_func };

pub const Replace = struct {
    pattern: []const u8,
    replacement: []const u8,
    global: bool = false,
    caseless: bool = false,
};

pub const MapEntry = struct {
    out: ?[]const u8,
    inputs: []const []const u8,
};

pub const Mapper = struct {
    entries: []const MapEntry,
    has_default: bool = false,
    default: ?[]const u8 = null,
};

pub const Prop = struct {
    field: Field,
    kind: PropKind,
    value: []const u8 = "",
    func: Function = .lowerize,
    replace: Replace = .{ .pattern = "", .replacement = "" },
    mapper: ?*const Mapper = null,
};

pub const Rule = struct {
    patterns: []const []const u8,
    props: []const Prop,
};

pub const browser_rules = [_]Rule{
    .{
        .patterns = &.{"\\b(?:crmo|crios)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Mobile Chrome" } },
    },
    .{
        .patterns = &.{"webview.+edge\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Edge WebView" } },
    },
    .{
        .patterns = &.{"edg(?:e|ios|a)?\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Edge" } },
    },
    .{
        .patterns = &.{ "(opera mini)\\/([-\\w\\.]+)", "(opera [mobiletab]{3,6})\\b.+version\\/([-\\w\\.]+)", "(opera)(?:.+version\\/|[\\/ ]+)([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"opios[\\/ ]+([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Opera Mini" } },
    },
    .{
        .patterns = &.{"\\bop(?:rg)?x\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Opera GX" } },
    },
    .{
        .patterns = &.{"\\bopr\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Opera" } },
    },
    .{
        .patterns = &.{"\\bb[ai]*d(?:uhd|[ub]*[aekoprswx]{5,6})[\\/ ]?([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Baidu" } },
    },
    .{
        .patterns = &.{"\\b(?:mxbrowser|mxios|myie2)\\/?([-\\w\\.]*)\\b"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Maxthon" } },
    },
    .{
        .patterns = &.{ "(kindle)\\/([\\w\\.]+)", "(lunascape|maxthon|netfront|jasmine|blazer|sleipnir)[\\/ ]?([\\w\\.]*)", "(avant|iemobile|slim(?:browser|boat|jet))[\\/ ]?([\\d\\.]*)", "(?:ms|\\()(ie) ([\\w\\.]+)", "(atlas|flock|rockmelt|midori|epiphany|silk|skyfire|bolt|iron|vivaldi|iridium|phantomjs|bowser|qupzilla|falkon|rekonq|puffin|whale(?!.+naver)|qqbrowserlite|duckduckgo|klar|helio|(?=comodo_)?dragon|otter|dooble|(?:hi|lg |ovi|qute)browser|palemoon)\\/v?([-\\w\\.]+)", "(brave)(?: chrome)?\\/([\\d\\.]+)", "(aloha|heytap|ovi|115|surf|qwant)browser\\/([\\d\\.]+)", "(qwant)(?:ios|mobile)\\/([\\d\\.]+)", "(ecosia|weibo)(?:__| \\w+@)([\\d\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"quark(?:pc)?\\/([-\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Quark" } },
    },
    .{
        .patterns = &.{"\\bddg\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "DuckDuckGo" } },
    },
    .{
        .patterns = &.{"(?:\\buc? ?browser|(?:juc.+)ucweb)[\\/ ]?([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "UCBrowser" } },
    },
    .{
        .patterns = &.{ "microm.+\\bqbcore\\/([\\w\\.]+)", "\\bqbcore\\/([\\w\\.]+).+microm", "micromessenger\\/([\\w\\.]+)" },
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "WeChat" } },
    },
    .{
        .patterns = &.{"konqueror\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Konqueror" } },
    },
    .{
        .patterns = &.{"trident.+rv[: ]([\\w\\.]{1,9})\\b.+like gecko"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "IE" } },
    },
    .{
        .patterns = &.{"ya(?:search)?browser\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Yandex" } },
    },
    .{
        .patterns = &.{"slbrowser\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Smart Lenovo Browser" } },
    },
    .{
        .patterns = &.{"(av(?:ast|g|ira))\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "(.+)",
            .replacement = "$1 Secure Browser",
            .global = false,
            .caseless = false,
        } }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"norton\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Norton Private Browser" } },
    },
    .{
        .patterns = &.{"\\bfocus\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Firefox Focus" } },
    },
    .{
        .patterns = &.{" mms\\/([\\w\\.]+)$"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Opera Neon" } },
    },
    .{
        .patterns = &.{" opt\\/([\\w\\.]+)$"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Opera Touch" } },
    },
    .{
        .patterns = &.{"coc_coc\\w+\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Coc Coc" } },
    },
    .{
        .patterns = &.{"dolfin\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Dolphin" } },
    },
    .{
        .patterns = &.{"coast\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Opera Coast" } },
    },
    .{
        .patterns = &.{"miuibrowser\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "MIUI Browser" } },
    },
    .{
        .patterns = &.{"fxios\\/([\\w\\.-]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Mobile Firefox" } },
    },
    .{
        .patterns = &.{"\\bqihoobrowser\\/?([\\w\\.]*)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "360" } },
    },
    .{
        .patterns = &.{"\\b(qq)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "(.+)",
            .replacement = "$1Browser",
            .global = false,
            .caseless = false,
        } }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"(oculus|sailfish|huawei|vivo|pico)browser\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "(.+)",
            .replacement = "$1 Browser",
            .global = false,
            .caseless = false,
        } }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"samsungbrowser\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Samsung Internet" } },
    },
    .{
        .patterns = &.{"metasr[\\/ ]?([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Sogou Explorer" } },
    },
    .{
        .patterns = &.{"(sogou)mo\\w+\\/([\\d\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Sogou Mobile" }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{ "(electron)\\/([\\w\\.]+) safari", "(tesla)(?: qtcarbrowser|\\/(20\\d\\d\\.[-\\w\\.]+))", "m?(qqbrowser|2345(?=browser|chrome|explorer))\\w*[\\/ ]?v?([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"(lbbrowser|luakit|rekonq|steam(?= (clie|tenf|gameo)))"},
        .props = &.{.{ .field = .name, .kind = .capture }},
    },
    .{
        .patterns = &.{"ome\\/([\\w\\.]+).+(iron(?= saf)|360(?=[es]e$))"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .capture } },
    },
    .{
        .patterns = &.{"((?:fban\\/fbios|fb_iab\\/fb4a)(?!.+fbav)|;fbav\\/([\\w\\.]+);)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Facebook" }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{ "(kakao(?:talk|story))[\\/ ]([\\w\\.]+)", "(naver)\\(.*?(\\d+\\.[\\w\\.]+).*\\)", "(daum)apps[\\/ ]([\\w\\.]+)", "safari (line)\\/([\\w\\.]+)", "\\b(line)\\/([\\w\\.]+)\\/iab", "(alipay)client\\/([\\w\\.]+)", "(twitter)(?:and| f.+e\\/([\\w\\.]+))", "(bing)(?:web|sapphire)\\/([\\w\\.]+)", "(instagram|snapchat|klarna)[\\/ ]([-\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"\\bgsa\\/([\\w\\.]+) .*safari\\/"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "GSA" }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"(?:musical_ly|trill)(?:.+app_?version\\/|_)([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "TikTok" }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"\\[(linkedin)app\\]"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"(zalo(?:app)?)[\\/\\sa-z]*([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "(.+)",
            .replacement = "Zalo",
            .global = false,
            .caseless = false,
        } }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"(chromium)[\\/ ]([-\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"ome-(lighthouse)$"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "fetcher" } },
    },
    .{
        .patterns = &.{"headlesschrome(?:\\/([\\w\\.]+)| )"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chrome Headless" } },
    },
    .{
        .patterns = &.{"wv\\).+chrome\\/([\\w\\.]+).+edgw\\/"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Edge WebView2" } },
    },
    .{
        .patterns = &.{" wv\\).+(chrome)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Chrome WebView" }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"droid.+ version\\/([\\w\\.]+)\\b.+(?:mobile safari|safari)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Android Browser" } },
    },
    .{
        .patterns = &.{"chrome\\/([\\w\\.]+) mobile"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Mobile Chrome" } },
    },
    .{
        .patterns = &.{"(chrome|omniweb|arora|[tizenoka]{5} ?browser)\\/v?([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"version\\/([\\w\\.\\,]+) .*mobile(?:\\/\\w+ | ?)safari"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Mobile Safari" } },
    },
    .{
        .patterns = &.{"iphone .*mobile(?:\\/\\w+ | ?)safari"},
        .props = &.{.{ .field = .name, .kind = .static, .value = "Mobile Safari" }},
    },
    .{
        .patterns = &.{"version\\/([\\w\\.\\,]+) .*(safari)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .capture } },
    },
    .{
        .patterns = &.{"webkit.+?(mobile ?safari|safari)(\\/[\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .static, .value = "1" } },
    },
    .{
        .patterns = &.{"(webkit|khtml)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"(?:mobile|tablet);.*(firefox)\\/([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Mobile Firefox" }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"(navigator|netscape\\d?)\\/([-\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Netscape" }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"(wolvic|librewolf)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"mobile vr; rv:([\\w\\.]+)\\).+firefox"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Firefox Reality" } },
    },
    .{
        .patterns = &.{ "ekiohf.+(flow)\\/([\\w\\.]+)", "(swiftfox)", "(icedragon|iceweasel|camino|chimera|fennec|maemo browser|minimo|conkeror)[\\/ ]?([\\w\\.\\+]+)", "(seamonkey|k-meleon|icecat|iceape|firebird|phoenix|basilisk|waterfox)\\/([-\\w\\.]+)$", "(firefox)\\/([\\w\\.]+)", "(mozilla)\\/([\\w\\.]+(?= .+rv\\:.+gecko\\/\\d+)|[0-4][\\w\\.]+(?!.+compatible))", "(amaya|dillo|doris|icab|ladybird|lynx|mosaic|netsurf|obigo|polaris|w3m|(?:go|ice|up)[\\. ]?browser)[-\\/ ]?v?([\\w\\.]+)", "\\b(links) \\(([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = ".",
            .global = true,
            .caseless = false,
        } } },
    },
    .{
        .patterns = &.{"(cobalt)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .replace, .replace = .{
            .pattern = "[^\\d\\.]+.",
            .replacement = "",
            .global = false,
            .caseless = false,
        } } },
    },
};

pub const cpu_rules = [_]Rule{
    .{
        .patterns = &.{"\\b((amd|x|x86[-_]?|wow|win)64)\\b"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "amd64" }},
    },
    .{
        .patterns = &.{ "(ia32(?=;))", "\\b((i[346]|x)86)(pc)?\\b" },
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "ia32" }},
    },
    .{
        .patterns = &.{"\\b(aarch64|arm(v?[89]e?l?|_?64))\\b"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "arm64" }},
    },
    .{
        .patterns = &.{"\\b(arm(v[67])?ht?n?[fl]p?)\\b"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "armhf" }},
    },
    .{
        .patterns = &.{"( (ce|mobile); ppc;|\\/[\\w\\.]+arm\\b)"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "arm" }},
    },
    .{
        .patterns = &.{" sun4\\w[;\\)]"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "sparc" }},
    },
    .{
        .patterns = &.{ "\\b(avr32|ia64(?=;)|68k(?=\\))|\\barm(?=v([1-7]|[5-7]1)l?|;|eabi)|(irix|mips|sparc)(64)?\\b|pa-risc)", "((ppc|powerpc)(64)?)( mac|;|\\))", "(?:osf1|[freopnt]{3,4}bsd) (alpha)" },
        .props = &.{.{ .field = .architecture, .kind = .replace_func, .replace = .{
            .pattern = "ower",
            .replacement = "",
            .global = false,
            .caseless = false,
        }, .func = .lowerize, .mapper = null }},
    },
    .{
        .patterns = &.{"mc680.0"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "68k" }},
    },
    .{
        .patterns = &.{"winnt.+\\[axp"},
        .props = &.{.{ .field = .architecture, .kind = .static, .value = "alpha" }},
    },
};

pub const device_rules = [_]Rule{
    .{
        .patterns = &.{"\\b(sch-i[89]0\\d|shw-m380s|sm-[ptx]\\w{2,4}|gt-[pn]\\d{2,4}|sgh-t8[56]9|nexus 10)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Samsung" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "\\b((?:s[cgp]h|gt|sm)-(?![lr])\\w+|sc[g-]?[\\d]+a?|galaxy nexus)", "samsung[- ]((?!sm-[lr]|browser)[-\\w]+)", "sec-(sgh\\w+)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Samsung" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(?:\\/|\\()(ip(?:hone|od)[\\w, ]*)[\\/\\);]"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Apple" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "\\b(?:ios|apple\\w+)\\/.+[\\(\\/](ipad)", "\\b(ipad)[\\d,]*[;\\] ].+(mac |i(pad)?)os" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Apple" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"(macintosh);"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Apple" } },
    },
    .{
        .patterns = &.{"\\b(sh-?[altvz]?\\d\\d[a-ekm]?)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Sharp" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b((?:brt|eln|hey2?|gdi|jdn)-a?[lnw]09|(?:ag[rm]3?|jdn2|kob2)-a?[lw]0[09]hn)(?: bui|\\)|;)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Honor" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"honor([-\\w ]+)[;\\)]"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Honor" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b((?:ag[rs][2356]?k?|bah[234]?|bg[2o]|bt[kv]|cmr|cpn|db[ry]2?|jdn2|got|kob2?k?|mon|pce|scm|sht?|[tw]gr|vrd)-[ad]?[lw][0125][09]b?|605hw|bg2-u03|(?:gem|fdr|m2|ple|t1)-[7a]0[1-4][lu]|t1-a2[13][lw]|mediapad[\\w\\. ]*(?= bui|\\)))\\b(?!.+d\\/s)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Huawei" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "(?:huawei) ?([-\\w ]+)[;\\)]", "\\b(nexus 6p|\\w{2,4}e?-[atu]?[ln][\\dx][\\dc][adnt]?)\\b(?!.+d\\/s)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Huawei" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "oid[^\\)]+; (2[\\dbc]{4}(182|283|rp\\w{2})[cgl]|m2105k81a?c)(?: bui|\\))", "\\b(?:xiao)?((?:red)?mi[-_ ]?pad[\\w- ]*)(?: bui|\\))" },
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = " ",
            .global = true,
            .caseless = false,
        } }, .{ .field = .vendor, .kind = .static, .value = "Xiaomi" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "\\b; (\\w+) build\\/hm\\1", "\\b(hm[-_ ]?note?[_ ]?(?:\\d\\w)?) bui", "oid[^\\)]+; (redmi[\\-_ ]?(?:note|k)?[\\w_ ]+|m?[12]\\d[01]\\d\\w{3,6}|poco[\\w ]+|(shark )?\\w{3}-[ah]0|qin ?[1-3](s\\+|ultra| pro)?)( bui|; wv|\\))", "\\b(mi[-_ ]?(?:a\\d|one|one[_ ]plus|note|max|cc)?[_ ]?(?:\\d{0,2}\\w?)[_ ]?(?:plus|se|lite|pro)?( 5g|lte)?)(?: bui|\\))", " ([\\w ]+) miui\\/v?\\d" },
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = " ",
            .global = true,
            .caseless = false,
        } }, .{ .field = .vendor, .kind = .static, .value = "Xiaomi" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "droid.+; (cph2[3-6]\\d[13579]|((gm|hd)19|(ac|be|in|kb)20|(d[en]|eb|le|mt)21|ne22)[0-2]\\d|p[g-l]\\w[1m]10)\\b", "(?:one)?(?:plus)? (a\\d0\\d\\d)(?: b|\\))" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "OnePlus" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "; (\\w+) bui.+ oppo", "\\b(cph[12]\\d{3}|p(?:af|c[al]|d\\w|e[ar])[mt]\\d0|x9007|a101op)\\b" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "OPPO" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(opd2(\\d{3}a?))(?: bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .func, .func = .str_mapper, .mapper = &mapper_device_14_1_0 }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"(vivo (5r?|6|8l?|go|one|s|x[il]?[2-4]?)[\\w\\+ ]*)(?: bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "BLU" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "; vivo (\\w+)(?: bui|\\))", "\\b(v[12]\\d{3}\\w?[at])(?: bui|;)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Vivo" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(rmx[1-3]\\d{3})(?: bui|;|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Realme" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "(ideatab[-\\w ]+|602lv|d-42a|a101lv|a2109a|a3500-hv|s[56]000|pb-6505[my]|tb-?x?\\d{3,4}(?:f[cu]|xu|[av])|yt\\d?-[jx]?\\d+[lfmx])( bui|;|\\)|\\/)", "lenovo ?(b[68]0[08]0-?[hf]?|tab(?:[\\w- ]+?)|tb[\\w-]{6,7})( bui|;|\\)|\\/)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Lenovo" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"lenovo[-_ ]?([-\\w ]+?)(?: bui|\\)|\\/)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Lenovo" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "\\b(milestone|droid(?:[2-4x]| (?:bionic|x2|pro|razr))?:?( 4g)?)\\b[\\w ]+build\\/", "\\bmot(?:orola)?[- ]([\\w\\s]+)(\\)| bui)", "((?:moto(?! 360)[-\\w\\(\\) ]+|xt\\d{3,4}[cgkosw\\+]?[-\\d]*|nexus 6)(?= bui|\\)))" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Motorola" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(mz60\\d|xoom[2 ]{0,2}) build\\/"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Motorola" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(?:lg)?([vl]k\\-?\\d{3}) bui| 3\\.[-\\w; ]{10}lg?-([06cv9]{3,4})"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "LG" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "(lm(?:-?f100[nv]?|-[\\w\\.]+)(?= bui|\\))|nexus [45])", "\\blg[-e;\\/ ]+(?!.*(?:browser|netcast|android tv|watch|webos))(\\w+)", "\\blg-?([\\d\\w]+) bui" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "LG" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(nokia) (t[12][01])"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "(?:maemo|nokia).*(n900|lumia \\d+|rm-\\d+)", "nokia[-_ ]?(([-\\w\\. ]*?))( bui|\\)|;|\\/)" },
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = " ",
            .global = true,
            .caseless = false,
        } }, .{ .field = .type, .kind = .static, .value = "mobile" }, .{ .field = .vendor, .kind = .static, .value = "Nokia" } },
    },
    .{
        .patterns = &.{"(pixel (c|tablet))\\b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"droid.+;(?: google)? (g(01[13]a|020[aem]|025[jn]|1b60|1f8f|2ybb|4s1m|576d|5nz6|8hhn|8vou|a02099|c15s|d1yq|e2ae|ec77|gh2x|kv4x|p4bc|pj41|r83y|tt9q|ur25|wvk6)|pixel[\\d ]*a?( pro)?( xl)?( fold)?( \\(5g\\))?)( bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(google) (pixelbook( go)?)"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture } },
    },
    .{
        .patterns = &.{"droid.+; (a?\\d[0-2]{2}so|[c-g]\\d{4}|so[-gl]\\w+|xq-\\w\\w\\d\\d)(?= bui|\\).+chrome\\/(?![1-6]{0,1}\\d\\.))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Sony" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "sony tablet [ps]", "\\b(?:sony)?sgp\\w+(?: bui|\\))" },
        .props = &.{ .{ .field = .model, .kind = .static, .value = "Xperia Tablet" }, .{ .field = .vendor, .kind = .static, .value = "Sony" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "(alexa)webm", "(kf[a-z]{2}wi|aeo(?!bc)\\w\\w)( bui|\\))", "(kf[a-z]+)( bui|\\)).+silk\\/" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Amazon" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"((?:sd|kf)[0349hijorstuw]+)( bui|\\)).+silk\\/"},
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "(.+)",
            .replacement = "Fire Phone $1",
            .global = true,
            .caseless = false,
        } }, .{ .field = .vendor, .kind = .static, .value = "Amazon" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(playbook);[-\\w\\),; ]+(rim)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "\\b((?:bb[a-f]|st[hv])100-\\d)", "(?:blackberry|\\(bb10;) (\\w+)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "BlackBerry" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(?:\\b|asus_)(transfo[prime ]{4,10} \\w+|eeepc|slider \\w+|nexus 7|padfone|p00[cj])"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "ASUS" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{" (z[bes]6[027][012][km][ls]|zenfone \\d\\w?)\\b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "ASUS" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(nexus 9)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "HTC" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "(htc)[-;_ ]{1,2}([\\w ]+(?=\\)| bui)|\\w+)", "(zte)[- ]([\\w ]+?)(?: bui|\\/|\\))", "(alcatel|geeksphone|nexian|panasonic(?!(?:;|\\.))|sony(?!-bra))[-_ ]?([-\\w]*)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = " ",
            .global = true,
            .caseless = false,
        } }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "tcl (xess p17aa)", "droid [\\w\\.]+; ((?:8[14]9[16]|9(?:0(?:48|60|8[01])|1(?:3[27]|66)|2(?:6[69]|9[56])|466))[gqswx])(_\\w(\\w|\\w\\w))?(\\)| bui)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "TCL" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"droid [\\w\\.]+; (418(?:7d|8v)|5087z|5102l|61(?:02[dh]|25[adfh]|27[ai]|56[dh]|59k|65[ah])|a509dl|t(?:43(?:0w|1[adepqu])|50(?:6d|7[adju])|6(?:09dl|10k|12b|71[efho]|76[hjk])|7(?:66[ahju]|67[hw]|7[045][bh]|71[hk]|73o|76[ho]|79w|81[hks]?|82h|90[bhsy]|99b)|810[hs]))(_\\w(\\w|\\w\\w))?(\\)| bui)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "TCL" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(itel) ((\\w+))"},
        .props = &.{ .{ .field = .vendor, .kind = .func, .func = .lowerize }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .func, .func = .str_mapper, .mapper = &mapper_device_41_2_1 } },
    },
    .{
        .patterns = &.{"droid.+; ([ab][1-7]-?[0178a]\\d\\d?)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Acer" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "droid.+; (m[1-5] note) bui", "\\bmz-([-\\w]{2,})" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Meizu" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"; ((?:power )?armor(?:[\\w ]{0,8}))(?: bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Ulefone" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "; (energy ?\\w+)(?: bui|\\))", "; energizer ([\\w ]+)(?: bui|\\))" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Energizer" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "; cat (b35);", "; (b15q?|s22 flip|s48c|s62 pro)(?: bui|\\))" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Cat" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"((?:new )?andromax[\\w- ]+)(?: bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Smartfren" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"droid.+; (a(in)?(0(15|59|6[35])|142)p?)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Nothing" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "; (x67 5g|tikeasy \\w+|ac[1789]\\d\\w+)( b|\\))", "archos ?(5|gamepad2?|([\\w ]*[t1789]|hello) ?\\d+[\\w ]*)( b|\\))" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Archos" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "archos ([\\w ]+)( b|\\))", "; (ac[3-6]\\d\\w{2,8})( b|\\))" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Archos" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"; (n159v)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "HMD" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "(imo) (tab \\w+)", "(infinix|tecno) (x1101b?|p904|dp(7c|8d|10a)( pro)?|p70[1-3]a?|p904|t1101)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "(blackberry|benq|palm(?=\\-)|sonyericsson|acer|asus(?! zenw)|dell|jolla|meizu|motorola|polytron|tecno|micromax|advan)[-_ ]?([-\\w]*)", "; (blu|hmd|imo|infinix|lava|oneplus|tcl|wiko)[_ ]([\\w\\+ ]+?)(?: bui|\\)|; r)", "(hp) ([\\w ]+\\w)", "(microsoft); (lumia[\\w ]+)", "(oppo) ?([\\w ]+) bui", "(hisense) ([ehv][\\w ]+)\\)", "droid[^;]+; (philips)[_ ]([sv-x][\\d]{3,4}[xz]?)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "(kobo)\\s(ereader|touch)", "(hp).+(touchpad(?!.+tablet)|tablet)", "(kindle)\\/([\\w\\.]+)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"(surface duo)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Microsoft" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"droid [\\d\\.]+; (fp\\du?)(?: b|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Fairphone" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"((?:tegranote|shield t(?!.+d tv))[\\w- ]*?)(?: b|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Nvidia" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"(sprint) (\\w+)"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"(kin\\.[onetw]{3})"},
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "\\.",
            .replacement = " ",
            .global = true,
            .caseless = false,
        } }, .{ .field = .vendor, .kind = .static, .value = "Microsoft" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"droid.+; ([c6]+|et5[16]|mc[239][23]x?|vc8[03]x?)\\)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Zebra" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"droid.+; (ec30|ps20|tc[2-8]\\d[kx])\\)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Zebra" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{ "(philips)[\\w ]+tv", "smart-tv.+(samsung)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"hbbtv.+maple;(\\d+)"},
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "^",
            .replacement = "SmartTV",
            .global = false,
            .caseless = false,
        } }, .{ .field = .vendor, .kind = .static, .value = "Samsung" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{ "(vizio)(?: |.+model\\/)(\\w+-\\w+)", "tcast.+(lg)e?. ([-\\w]+)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(nux; netcast.+smarttv|lg (netcast\\.tv-201\\d|android tv))"},
        .props = &.{ .{ .field = .vendor, .kind = .static, .value = "LG" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(apple) ?tv"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .static, .value = "Apple TV" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"crkey.*devicetype\\/chromecast"},
        .props = &.{ .{ .field = .model, .kind = .static, .value = "Chromecast Third Generation" }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"crkey.*devicetype\\/([^/]*)"},
        .props = &.{ .{ .field = .model, .kind = .replace, .replace = .{
            .pattern = "^",
            .replacement = "Chromecast ",
            .global = false,
            .caseless = false,
        } }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"fuchsia.*crkey"},
        .props = &.{ .{ .field = .model, .kind = .static, .value = "Chromecast Nest Hub" }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"crkey"},
        .props = &.{ .{ .field = .model, .kind = .static, .value = "Chromecast" }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(portaltv)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Facebook" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"droid.+aft(\\w+)( bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Amazon" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(shield \\w+ tv)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Nvidia" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{ "\\(dtv[\\);].+(aquos)", "(aquos-tv[\\w ]+)\\)" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Sharp" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(bravia[\\w ]+)( bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Sony" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(mi(tv|box)-?\\w+) bui"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Xiaomi" }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"Hbbtv.*(technisat) (.*);"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{ "\\b(roku)[\\dx]*[\\)\\/]((?:dvp-)?[\\d\\.]*)", "hbbtv\\/\\d+\\.\\d+\\.\\d+ +\\([\\w\\+ ]*; *([\\w\\d][^;]*);([^;]*)" },
        .props = &.{ .{ .field = .vendor, .kind = .replace_func, .replace = .{
            .pattern = ".+\\/(\\w+)",
            .replacement = "$1",
            .global = false,
            .caseless = false,
        }, .func = .str_mapper, .mapper = &mapper_device_78_0_2 }, .{ .field = .model, .kind = .func, .func = .trim }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"(playstation \\w+)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Sony" }, .{ .field = .type, .kind = .static, .value = "console" } },
    },
    .{
        .patterns = &.{"\\b(xbox(?: one)?(?!; xbox))[\\); ]"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Microsoft" }, .{ .field = .type, .kind = .static, .value = "console" } },
    },
    .{
        .patterns = &.{ "(ouya)", "(nintendo) (\\w+)", "(retroid) (pocket ([^\\)]+))", "(valve).+(steam deck)", "droid.+; ((shield|rgcube|gr0006))( bui|\\))" },
        .props = &.{ .{ .field = .vendor, .kind = .func, .func = .str_mapper, .mapper = &mapper_device_81_0_3 }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "console" } },
    },
    .{
        .patterns = &.{"\\b(sm-[lr]\\d\\d[0156][fnuw]?s?|gear live)\\b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Samsung" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{ "((pebble))app", "(asus|google|lg|oppo|xiaomi) ((pixel |zen)?watch[\\w ]*)( bui|\\))" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"(ow(?:19|20)?we?[1-3]{1,3})"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "OPPO" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"(watch)(?: ?os[,\\/]|\\d,\\d\\/)[\\d\\.]+"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Apple" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"(opwwe\\d{3})"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "OnePlus" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"(moto 360)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Motorola" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"(smartwatch 3)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Sony" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"(g watch r)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "LG" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"droid.+; (wt63?0{2,3})\\)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Zebra" }, .{ .field = .type, .kind = .static, .value = "wearable" } },
    },
    .{
        .patterns = &.{"droid.+; (glass) \\d"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Google" }, .{ .field = .type, .kind = .static, .value = "xr" } },
    },
    .{
        .patterns = &.{"(pico) ([\\w ]+) os\\d"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "xr" } },
    },
    .{
        .patterns = &.{"(quest( \\d| pro)?s?).+vr"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Facebook" }, .{ .field = .type, .kind = .static, .value = "xr" } },
    },
    .{
        .patterns = &.{"mobile vr; rv.+firefox"},
        .props = &.{.{ .field = .type, .kind = .static, .value = "xr" }},
    },
    .{
        .patterns = &.{"(tesla)(?: qtcarbrowser|\\/[-\\w\\.]+)"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "embedded" } },
    },
    .{
        .patterns = &.{"(aeobc)\\b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Amazon" }, .{ .field = .type, .kind = .static, .value = "embedded" } },
    },
    .{
        .patterns = &.{"(homepod).+mac os"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Apple" }, .{ .field = .type, .kind = .static, .value = "embedded" } },
    },
    .{
        .patterns = &.{"windows iot"},
        .props = &.{.{ .field = .type, .kind = .static, .value = "embedded" }},
    },
    .{
        .patterns = &.{"droid.+; ([\\w- ]+) (4k|android|smart|google)[- ]?tv"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "smarttv" } },
    },
    .{
        .patterns = &.{"\\b((4k|android|smart|opera)[- ]?tv|tv; rv:|large screen[\\w ]+safari)\\b"},
        .props = &.{.{ .field = .type, .kind = .static, .value = "smarttv" }},
    },
    .{
        .patterns = &.{"droid .+?; ([^;]+?)(?: bui|; wv\\)|\\) applew|; hmsc).+?(mobile|vr|\\d) safari"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .func, .func = .str_mapper, .mapper = &mapper_device_101_1_4 } },
    },
    .{
        .patterns = &.{"\\b((tablet|tab)[;\\/]|focus\\/\\d(?!.+mobile))"},
        .props = &.{.{ .field = .type, .kind = .static, .value = "tablet" }},
    },
    .{
        .patterns = &.{"(phone|mobile(?:[;\\/]| [ \\w\\/\\.]*safari)|pda(?=.+windows ce))"},
        .props = &.{.{ .field = .type, .kind = .static, .value = "mobile" }},
    },
    .{
        .patterns = &.{"droid .+?; ([\\w\\. -]+)( bui|\\))"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Generic" } },
    },
};

pub const engine_rules = [_]Rule{
    .{
        .patterns = &.{"windows.+ edge\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "EdgeHTML" } },
    },
    .{
        .patterns = &.{"(arkweb)\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"webkit\\/537\\.36.+chrome\\/(?!27)([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Blink" } },
    },
    .{
        .patterns = &.{ "(presto)\\/([\\w\\.]+)", "(webkit|trident|netfront|netsurf|amaya|lynx|w3m|goanna|servo)\\/([\\w\\.]+)", "ekioh(flow)\\/([\\w\\.]+)", "(khtml|tasman|links|dillo)[\\/ ]\\(?([\\w\\.]+)", "(icab)[\\/ ]([23]\\.[\\d\\.]+)", "\\b(libweb)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"ladybird\\/"},
        .props = &.{.{ .field = .name, .kind = .static, .value = "LibWeb" }},
    },
    .{
        .patterns = &.{"rv\\:([\\w\\.]{1,9})\\b.+(gecko)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .capture } },
    },
};

pub const os_rules = [_]Rule{
    .{
        .patterns = &.{"(windows nt) (6\\.[23]); arm"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "N",
            .replacement = "R",
            .global = false,
            .caseless = false,
        } }, .{ .field = .version, .kind = .func, .func = .str_mapper, .mapper = &mapper_os_0_1_5 } },
    },
    .{
        .patterns = &.{ "(windows (?:phone|mobile|iot))(?: os)?[\\/ ]?([\\d\\.]*( se)?)", "(windows)[\\/ ](1[01]|2000|3\\.1|7|8(\\.1)?|9[58]|me|server 20\\d\\d( r2)?|vista|xp)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{ "windows nt ?([\\d\\.\\)]*)(?!.+xbox)", "\\bwin(?=3| ?9|n)(?:nt| 9x )?([\\d\\.;]*)" },
        .props = &.{ .{ .field = .version, .kind = .replace_func, .replace = .{
            .pattern = "(;|\\))",
            .replacement = "",
            .global = true,
            .caseless = false,
        }, .func = .str_mapper, .mapper = &mapper_os_2_0_6 }, .{ .field = .name, .kind = .static, .value = "Windows" } },
    },
    .{
        .patterns = &.{"(windows ce)\\/?([\\d\\.]*)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{ "[adehimnop]{4,7}\\b(?:.*os ([\\w]+) like mac|; opera)", "(?:ios;fbsv|ios(?=.+ip(?:ad|hone)|.+apple ?tv)|ip(?:ad|hone)(?: |.+i(?:pad)?)os|apple ?tv.+ios)[\\/ ]([\\w\\.]+)", "\\btvos ?([\\w\\.]+)", "cfnetwork\\/.+darwin" },
        .props = &.{ .{ .field = .version, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = ".",
            .global = true,
            .caseless = false,
        } }, .{ .field = .name, .kind = .static, .value = "iOS" } },
    },
    .{
        .patterns = &.{ "(mac os x) ?([\\w\\. ]*)", "(macintosh|mac_powerpc\\b)(?!.+(haiku|morphos))" },
        .props = &.{ .{ .field = .name, .kind = .static, .value = "macOS" }, .{ .field = .version, .kind = .replace, .replace = .{
            .pattern = "_",
            .replacement = ".",
            .global = true,
            .caseless = false,
        } } },
    },
    .{
        .patterns = &.{"android ([\\d\\.]+).*crkey"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chromecast Android" } },
    },
    .{
        .patterns = &.{"fuchsia.*crkey\\/([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chromecast Fuchsia" } },
    },
    .{
        .patterns = &.{"crkey\\/([\\d\\.]+).*devicetype\\/smartspeaker"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chromecast SmartSpeaker" } },
    },
    .{
        .patterns = &.{"linux.*crkey\\/([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chromecast Linux" } },
    },
    .{
        .patterns = &.{"crkey\\/([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chromecast" } },
    },
    .{
        .patterns = &.{"droid ([\\w\\.]+)\\b.+(android[- ]x86)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .capture } },
    },
    .{
        .patterns = &.{"(ubuntu) ([\\w\\.]+) like android"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "(.+)",
            .replacement = "$1 Touch",
            .global = false,
            .caseless = false,
        } }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{ "(harmonyos)[\\/ ]?([\\d\\.]*)", "(android|bada|blackberry|kaios|maemo|meego|openharmony|qnx|rim tablet os|sailfish|series40|symbian|tizen)\\w*[-\\/\\.; ]?([\\d\\.]*)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"\\(bb(10);"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "BlackBerry" } },
    },
    .{
        .patterns = &.{"(?:symbian ?os|symbos|s60(?=;)|series ?60)[-\\/ ]?([\\w\\.]*)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Symbian" } },
    },
    .{
        .patterns = &.{"mozilla\\/[\\d\\.]+ \\((?:mobile[;\\w ]*|tablet|tv|[^\\)]*(?:viera|lg(?:l25|-d300)|alcatel ?o.+|y300-f1)); rv:([\\w\\.]+)\\).+gecko\\/"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Firefox OS" } },
    },
    .{
        .patterns = &.{ "\\b(?:hp)?wos(?:browser)?\\/([\\w\\.]+)", "webos(?:[ \\/]?|\\.tv-20(?=2[2-9]))(\\d[\\d\\.]*)" },
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "webOS" } },
    },
    .{
        .patterns = &.{"web0s;.+?(?:chr[o0]me|safari)\\/(\\d+)"},
        .props = &.{ .{ .field = .version, .kind = .func, .func = .str_mapper, .mapper = &mapper_os_18_0_7 }, .{ .field = .name, .kind = .static, .value = "webOS" } },
    },
    .{
        .patterns = &.{"watch(?: ?os[,\\/ ]|\\d,\\d\\/)([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "watchOS" } },
    },
    .{
        .patterns = &.{"cros [\\w]+(?:\\)| ([\\w\\.]+)\\b)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Chrome OS" } },
    },
    .{
        .patterns = &.{"kepler ([\\w\\.]+); (aft|aeo)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Vega OS" } },
    },
    .{
        .patterns = &.{ "(netrange)mmh", "(nettv)\\/(\\d+\\.[\\w\\.]+)", "(nintendo|playstation) (\\w+)", "(xbox); +xbox ([^\\);]+)", "(pico) .+os([\\w\\.]+)", "\\b(joli|palm)\\b ?(?:os)?\\/?([\\w\\.]*)", "linux.+(mint)[\\/\\(\\) ]?([\\w\\.]*)", "(mageia|vectorlinux|fuchsia|arcaos|arch(?= ?linux))[;l ]([\\d\\.]*)", "([kxln]?ubuntu|debian|suse|opensuse|gentoo|slackware|fedora|mandriva|centos|pclinuxos|red ?hat|zenwalk|linpus|raspbian|plan 9|minix|risc os|contiki|deepin|manjaro|elementary os|sabayon|linspire|knoppix)(?: gnu[\\/ ]linux)?(?: enterprise)?(?:[- ]linux)?(?:-gnu)?[-\\/ ]?(?!chrom|package)([-\\w\\.]*)", "((?:open)?solaris)[-\\/ ]?([\\w\\.]*)", "\\b(aix)[; ]([1-9\\.]{0,4})", "(hurd|linux|morphos)(?: (?:arm|x86|ppc)\\w*| ?)([\\w\\.]*)", "(gnu) ?([\\w\\.]*)", "\\b([-frentopcghs]{0,5}bsd|dragonfly)[\\/ ]?(?!amd|[ix346]{1,2}86)([\\w\\.]*)", "(haiku) ?(r\\d)?" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{"(sunos) ?([\\d\\.]*)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Solaris" }, .{ .field = .version, .kind = .capture } },
    },
    .{
        .patterns = &.{ "\\b(beos|os\\/2|amigaos|openvms|hp-ux|serenityos)", "(unix) ?([\\w\\.]*)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture } },
    },
};

const mapper_device_14_1_0 = Mapper{
    .entries = &.{
        .{ .out = "OnePlus", .inputs = &.{ "203", "304", "403", "404", "413", "415" } },
    },
    .has_default = true,
    .default = "OPPO",
};

const mapper_device_41_2_1 = Mapper{
    .entries = &.{
        .{ .out = "tablet", .inputs = &.{ "p10001l", "w7001" } },
    },
    .has_default = true,
    .default = "mobile",
};

const mapper_device_78_0_2 = Mapper{
    .entries = &.{
        .{ .out = "LG", .inputs = &.{"lge"} },
    },
    .has_default = false,
    .default = null,
};

const mapper_device_81_0_3 = Mapper{
    .entries = &.{
        .{ .out = "Nvidia", .inputs = &.{"Shield"} },
        .{ .out = "Anbernic", .inputs = &.{"RGCUBE"} },
        .{ .out = "Logitech", .inputs = &.{"GR0006"} },
    },
    .has_default = false,
    .default = null,
};

const mapper_device_101_1_4 = Mapper{
    .entries = &.{
        .{ .out = "mobile", .inputs = &.{"Mobile"} },
        .{ .out = "xr", .inputs = &.{"VR"} },
    },
    .has_default = true,
    .default = "tablet",
};

const mapper_os_0_1_5 = Mapper{
    .entries = &.{
        .{ .out = "7", .inputs = &.{"6.1"} },
        .{ .out = "8", .inputs = &.{"6.2"} },
        .{ .out = "10", .inputs = &.{ "6.4", "10.0" } },
        .{ .out = "2000", .inputs = &.{ "5.0", "5.01" } },
        .{ .out = "ME", .inputs = &.{"4.90"} },
        .{ .out = "NT 3.51", .inputs = &.{"3.51"} },
        .{ .out = "NT 4.0", .inputs = &.{"4.0"} },
        .{ .out = "XP", .inputs = &.{ "5.1", "5.2" } },
        .{ .out = "Vista", .inputs = &.{"6.0"} },
        .{ .out = "8.1", .inputs = &.{"6.3"} },
        .{ .out = "NT", .inputs = &.{""} },
    },
    .has_default = false,
    .default = null,
};

const mapper_os_2_0_6 = Mapper{
    .entries = &.{
        .{ .out = "7", .inputs = &.{"6.1"} },
        .{ .out = "8", .inputs = &.{"6.2"} },
        .{ .out = "10", .inputs = &.{ "6.4", "10.0" } },
        .{ .out = "2000", .inputs = &.{ "5.0", "5.01" } },
        .{ .out = "ME", .inputs = &.{"4.90"} },
        .{ .out = "NT 3.51", .inputs = &.{"3.51"} },
        .{ .out = "NT 4.0", .inputs = &.{"4.0"} },
        .{ .out = "XP", .inputs = &.{ "5.1", "5.2" } },
        .{ .out = "Vista", .inputs = &.{"6.0"} },
        .{ .out = "8.1", .inputs = &.{"6.3"} },
        .{ .out = "NT", .inputs = &.{""} },
    },
    .has_default = false,
    .default = null,
};

const mapper_os_18_0_7 = Mapper{
    .entries = &.{
        .{ .out = "1", .inputs = &.{"537"} },
        .{ .out = "2", .inputs = &.{"538"} },
        .{ .out = "3", .inputs = &.{"38"} },
        .{ .out = "4", .inputs = &.{"53"} },
        .{ .out = "5", .inputs = &.{"68"} },
        .{ .out = "6", .inputs = &.{"79"} },
        .{ .out = "22", .inputs = &.{"87"} },
        .{ .out = "23", .inputs = &.{"94"} },
        .{ .out = "24", .inputs = &.{"108"} },
        .{ .out = "25", .inputs = &.{"120"} },
    },
    .has_default = true,
    .default = "TV",
};
