// Generated by tools/generate_ua_parser_extensions.mjs from ua-parser-js v2.0.9.
// Do not edit by hand.

const base = @import("ua_parser_tables.zig");
const Rule = base.Rule;
const Mapper = base.Mapper;

pub const bots_browser_rules = [_]Rule{
    .{
        .patterns = &.{"(wget|curl|lynx|elinks|httpie|powershell)[\\/ ]\\(?([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "cli" } },
    },
    .{
        .patterns = &.{ "(asana|ahrefssiteaudit|(?:bing|microsoft)preview|blueno|(?:chatgpt|claude|mistralai|perplexity)-user|cohere-ai|flipboardproxy|hubspot page fetcher|mastodon|(?:bitly|bufferlinkpreview|discord|duckassist|linkedin|pinterest|reddit|roger|siteaudit|twitter|uptimero|zoom)bot|google-site-verification|iframely|kakaotalk-scrap|meta-externalfetcher|y!?j-dlc|yandex(?:calendar|direct(?:dyn)?|fordomain|pagechecker|searchshop)|yadirectfetcher|whatsapp)\\/([\\w\\.]+)", "(bluesky) cardyb\\/([\\w\\.]+)", "agent-(novaact)\\/([\\w\\.]+)", "(skypeuripreview) preview\\/([\\w\\.]+)", "(slack(?:bot)?(?:-imgproxy|-linkexpanding)?) ([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "fetcher" } },
    },
    .{
        .patterns = &.{"((?:better uptime |keybase|telegram|vercel)bot|lighthouse$|feedfetcher-google|gemini-deep-research|google(?:imageproxy|-read-aloud|-pagerenderer|producer)|snap url preview|vercel(flags|tracing|-(favicon|screenshot)-bot)|yandex(?:sitelinks|userproxy))"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "fetcher" } },
    },
    .{
        .patterns = &.{ "((?:adidx|ahrefs|amazon|bing|brave|cc|contx|coveo|criteo|dot|duckduck(?:go-favicons-)?|exa|facebook|gpt|iask|kagi|kangaroo |linkedin|mj12|mojeek|oai-search|onespot-scraper|perplexity|sbintuitions|semrush|seznam|surdotly|swift|yep)bot)\\/([\\w\\.-]+)", "(algolia crawler(?: renderscript)?)\\/?([\\w\\.]*)", "(applebot(?:-extended)?)\\/?([\\w\\.]*)", "(baiduspider[-imagevdonwsfcpr]{0,7})\\/?([\\w\\.]*)", "(claude(?:bot|-searchbot|-web)|anthropic-ai)\\/?([\\w\\.]*)", "(coccocbot-(?:image|web))\\/([\\w\\.]+)", "(daum(?:oa)?(?:-image)?)[ \\/]([\\w\\.]+)", "(facebook(?:externalhit|catalog)|meta-externalagent)\\/([\\w\\.]+)", "(google(?:bot|other|-inspectiontool)(?:-image|-video|-news)?|storebot-google)\\/?([\\w\\.]*)", "(ia_archiver|archive\\.org_bot)\\/?([\\w\\.]*)", "(oncrawl) mobile\\/([\\w\\.]+)", "(qwantbot(?:-news)?)[-\\w]*\\/?([\\w\\.]*)", "((?:semrush|splitsignal)bot[-abcfimostw]*)\\/?([\\w\\.-]*)", "(sogou (?:pic|head|web|orion|news) spider)\\/([\\w\\.]+)", "(y!?j-(?:asr|br[uw]|dscv|mmp|vsidx|wsc))\\/([\\w\\.]+)", "(yandex(?:(?:mobile)?(?:accessibility|additional|com|renderresources|screenshot|sprav)?bot(?!.+mirror)|image(?:s|resizer)|adnet|blogs|favicons|market|media|metrika|news|ontodb(?:api)?|partner|rca|tracker|turbo|verti(?:cal)?s|webmaster|video(?:parser)?))\\/([\\w\\.]+)", "(yeti)\\/([\\w\\.]+)", "((?:aihit|blex|diff|huggingface-|msn|pangu|replicate-|runpod-|timpi|together-|xai-|you|zum)bot|(?:magpie-|velenpublicweb)crawler|(?:chatglm-|line|screaming frog seo |yisou)spider|cloudflare-autorag|cotoyogi|(?:firecrawl|twin)agent|freespoke|omgili(?:bot)?|openai image downloader|startpageprivateimageproxy|webzio-extended)\\/?([\\w\\.]*)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "crawler" } },
    },
    .{
        .patterns = &.{"(yandexbot\\/([\\w\\.]+); mirrordetector)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "\\/.+;",
            .replacement = "",
            .global = true,
            .caseless = true,
        } }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "crawler" } },
    },
    .{
        .patterns = &.{ "((?:adsbot|apis|mediapartners)-google(?:-mobile)?|google-?(?:other|cloudvertexbot|extended|notebooklm|safety))", "\\b((ai2|aspiegel|atlassian-|dataforseo|deepseek|imagesift|petal|seekport|turnitin|v0)bot|360spider-?(image|video)?|baidu-ads|botify|(byte|tiktok)spider|cohere-training-data-crawler|elastic(?=\\/s)|marginalia|siteimprove(?=bot|\\.com)|teoma|webzio|yahoo! slurp)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "crawler" } },
    },
    .{
        .patterns = &.{ "^((?:apache|go|java)-http-?client|axios|bun|dart|deno|got|(?:guzzle|lua-resty-|ocaml-co|ok)http|hackney|http\\.rb|java|jetty|libwww-perl|needle|node(?:\\.js|-fetch|-superagent)|php-soap|postmanruntime|python-(?:httpx|urllib[23]?|requests)|rest-client|scrapy)\\/([\\w\\.]+)", "(adobeair|aiohttp|jsdom)\\/([\\w\\.]+)", "(nutch)-([\\w\\.-]+)(\\(|$)", "\\((java)\\/([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "library" } },
    },
    .{
        .patterns = &.{"(node-fetch|undici)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "library" } },
    },
};

pub const bots_cpu_rules = [_]Rule{};

pub const bots_device_rules = [_]Rule{};

pub const bots_engine_rules = [_]Rule{};

pub const bots_os_rules = [_]Rule{
    .{
        .patterns = &.{"whatsapp\\/[\\d\\.]+ (a|i)"},
        .props = &.{.{ .field = .name, .kind = .func, .func = .whatsapp_os }},
    },
};

pub const clis_browser_rules = [_]Rule{
    .{
        .patterns = &.{"(wget|curl|lynx|elinks|httpie|powershell)[\\/ ]\\(?([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "cli" } },
    },
};

pub const clis_cpu_rules = [_]Rule{};

pub const clis_device_rules = [_]Rule{};

pub const clis_engine_rules = [_]Rule{};

pub const clis_os_rules = [_]Rule{};

pub const crawlers_browser_rules = [_]Rule{
    .{
        .patterns = &.{ "((?:adidx|ahrefs|amazon|bing|brave|cc|contx|coveo|criteo|dot|duckduck(?:go-favicons-)?|exa|facebook|gpt|iask|kagi|kangaroo |linkedin|mj12|mojeek|oai-search|onespot-scraper|perplexity|sbintuitions|semrush|seznam|surdotly|swift|yep)bot)\\/([\\w\\.-]+)", "(algolia crawler(?: renderscript)?)\\/?([\\w\\.]*)", "(applebot(?:-extended)?)\\/?([\\w\\.]*)", "(baiduspider[-imagevdonwsfcpr]{0,7})\\/?([\\w\\.]*)", "(claude(?:bot|-searchbot|-web)|anthropic-ai)\\/?([\\w\\.]*)", "(coccocbot-(?:image|web))\\/([\\w\\.]+)", "(daum(?:oa)?(?:-image)?)[ \\/]([\\w\\.]+)", "(facebook(?:externalhit|catalog)|meta-externalagent)\\/([\\w\\.]+)", "(google(?:bot|other|-inspectiontool)(?:-image|-video|-news)?|storebot-google)\\/?([\\w\\.]*)", "(ia_archiver|archive\\.org_bot)\\/?([\\w\\.]*)", "(oncrawl) mobile\\/([\\w\\.]+)", "(qwantbot(?:-news)?)[-\\w]*\\/?([\\w\\.]*)", "((?:semrush|splitsignal)bot[-abcfimostw]*)\\/?([\\w\\.-]*)", "(sogou (?:pic|head|web|orion|news) spider)\\/([\\w\\.]+)", "(y!?j-(?:asr|br[uw]|dscv|mmp|vsidx|wsc))\\/([\\w\\.]+)", "(yandex(?:(?:mobile)?(?:accessibility|additional|com|renderresources|screenshot|sprav)?bot(?!.+mirror)|image(?:s|resizer)|adnet|blogs|favicons|market|media|metrika|news|ontodb(?:api)?|partner|rca|tracker|turbo|verti(?:cal)?s|webmaster|video(?:parser)?))\\/([\\w\\.]+)", "(yeti)\\/([\\w\\.]+)", "((?:aihit|blex|diff|huggingface-|msn|pangu|replicate-|runpod-|timpi|together-|xai-|you|zum)bot|(?:magpie-|velenpublicweb)crawler|(?:chatglm-|line|screaming frog seo |yisou)spider|cloudflare-autorag|cotoyogi|(?:firecrawl|twin)agent|freespoke|omgili(?:bot)?|openai image downloader|startpageprivateimageproxy|webzio-extended)\\/?([\\w\\.]*)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "crawler" } },
    },
    .{
        .patterns = &.{"(yandexbot\\/([\\w\\.]+); mirrordetector)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "\\/.+;",
            .replacement = "",
            .global = true,
            .caseless = true,
        } }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "crawler" } },
    },
    .{
        .patterns = &.{ "((?:adsbot|apis|mediapartners)-google(?:-mobile)?|google-?(?:other|cloudvertexbot|extended|notebooklm|safety))", "\\b((ai2|aspiegel|atlassian-|dataforseo|deepseek|imagesift|petal|seekport|turnitin|v0)bot|360spider-?(image|video)?|baidu-ads|botify|(byte|tiktok)spider|cohere-training-data-crawler|elastic(?=\\/s)|marginalia|siteimprove(?=bot|\\.com)|teoma|webzio|yahoo! slurp)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "crawler" } },
    },
};

pub const crawlers_cpu_rules = [_]Rule{};

pub const crawlers_device_rules = [_]Rule{};

pub const crawlers_engine_rules = [_]Rule{};

pub const crawlers_os_rules = [_]Rule{};

pub const extra_devices_browser_rules = [_]Rule{};

pub const extra_devices_cpu_rules = [_]Rule{};

pub const extra_devices_device_rules = [_]Rule{
    .{
        .patterns = &.{ "(nook)[\\w ]+build\\/(\\w+)", "(dell) (strea[kpr\\d ]*[\\dko])", "(le[- ]+pan)[- ]+(\\w{1,9}) bui", "(trinity)[- ]*(t\\d{3}) bui", "(gigaset)[- ]+(q\\w{1,9}) bui", "(vodafone) ([\\w ]+)(?:\\)| bui)" },
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"(u304aa)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "AT&T" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\bsie-(\\w*)"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Siemens" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(rct\\w+) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "RCA" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(venue[\\d ]{2,7}) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Dell" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(q(?:mv|ta)\\w+) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Verizon" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(?:barnes[& ]+noble |bn[rt])([\\w\\+ ]*) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Barnes & Noble" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(tm\\d{3}\\w+) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "NuVision" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(k88) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "ZTE" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(nx\\d{3}j) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "ZTE" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(gen\\d{3}) b.+49h"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Swiss" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(zur\\d{3}) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Swiss" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"^((zeki)?tb.*\\b) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Zeki" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{ "\\b([yr]\\d{2}) b", "\\b(?:dragon[- ]+touch |dt)(\\w{5}) b" },
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Dragon Touch" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(ns-?\\w{0,9}) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Insignia" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b((nxa|next)-?\\w{0,9}) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "NextBook" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(xtreme\\_)?(v(1[045]|2[015]|[3469]0|7[05])) b"},
        .props = &.{ .{ .field = .vendor, .kind = .static, .value = "Voice" }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(lvtel\\-)?(v1[12]) b"},
        .props = &.{ .{ .field = .vendor, .kind = .static, .value = "LvTel" }, .{ .field = .model, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(ph-1) "},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Essential" }, .{ .field = .type, .kind = .static, .value = "mobile" } },
    },
    .{
        .patterns = &.{"\\b(v(100md|700na|7011|917g).*\\b) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Envizen" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\b(trio[-\\w\\. ]+) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "MachSpeed" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
    .{
        .patterns = &.{"\\btu_(1491) b"},
        .props = &.{ .{ .field = .model, .kind = .capture }, .{ .field = .vendor, .kind = .static, .value = "Rotor" }, .{ .field = .type, .kind = .static, .value = "tablet" } },
    },
};

pub const extra_devices_engine_rules = [_]Rule{};

pub const extra_devices_os_rules = [_]Rule{};

pub const emails_browser_rules = [_]Rule{
    .{
        .patterns = &.{"(android)\\/([\\w\\.-]+email)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "email" } },
    },
    .{
        .patterns = &.{"((?:air|aqua|blue|claws|daum|fair|fox|k-9|mac|nylas|pegasus|poco|poly|proton|samsung|squirrel|yahoo) ?e?mail(?:-desktop| app| bridge)?|microsoft outlook|r2mail2|spicebird|turnpike|yahoomobile|(?:microsoft )?outlook(?:-express)?|macoutlook|windows-live-mail|alpine|balsa|barca|canary|emclient|eudora|evolution|geary|gnus|horde::imp|incredimail|kmail2?|kontact|lotus-notes|mail(?:bird|mate|spring)|mutt|navermailapp|newton|nine|postbox|rainloop|roundcube webmail|spar(?:row|kdesktop)|sylpheed|the bat!|thunderbird|trojita|tutanota-desktop|wanderlust|zdesktop|zohomail-desktop)(?:m.+ail; |[\\/ ])([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .func, .func = .normalize_email_name }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "email" } },
    },
    .{
        .patterns = &.{"(mail)\\/([\\w\\.]+) cf"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "email" } },
    },
    .{
        .patterns = &.{"(zimbra)\\/([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "email" } },
    },
};

pub const emails_cpu_rules = [_]Rule{};

pub const emails_device_rules = [_]Rule{};

pub const emails_engine_rules = [_]Rule{};

pub const emails_os_rules = [_]Rule{};

pub const fetchers_browser_rules = [_]Rule{
    .{
        .patterns = &.{ "(asana|ahrefssiteaudit|(?:bing|microsoft)preview|blueno|(?:chatgpt|claude|mistralai|perplexity)-user|cohere-ai|flipboardproxy|hubspot page fetcher|mastodon|(?:bitly|bufferlinkpreview|discord|duckassist|linkedin|pinterest|reddit|roger|siteaudit|twitter|uptimero|zoom)bot|google-site-verification|iframely|kakaotalk-scrap|meta-externalfetcher|y!?j-dlc|yandex(?:calendar|direct(?:dyn)?|fordomain|pagechecker|searchshop)|yadirectfetcher|whatsapp)\\/([\\w\\.]+)", "(bluesky) cardyb\\/([\\w\\.]+)", "agent-(novaact)\\/([\\w\\.]+)", "(skypeuripreview) preview\\/([\\w\\.]+)", "(slack(?:bot)?(?:-imgproxy|-linkexpanding)?) ([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "fetcher" } },
    },
    .{
        .patterns = &.{"((?:better uptime |keybase|telegram|vercel)bot|lighthouse$|feedfetcher-google|gemini-deep-research|google(?:imageproxy|-read-aloud|-pagerenderer|producer)|snap url preview|vercel(flags|tracing|-(favicon|screenshot)-bot)|yandex(?:sitelinks|userproxy))"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "fetcher" } },
    },
};

pub const fetchers_cpu_rules = [_]Rule{};

pub const fetchers_device_rules = [_]Rule{};

pub const fetchers_engine_rules = [_]Rule{};

pub const fetchers_os_rules = [_]Rule{
    .{
        .patterns = &.{"whatsapp\\/[\\d\\.]+ (a|i)"},
        .props = &.{.{ .field = .name, .kind = .func, .func = .whatsapp_os }},
    },
};

pub const inapps_browser_rules = [_]Rule{
    .{
        .patterns = &.{ "\\b(discord|figma|mattermost|notion|postman|rambox|rocket.chat|slack|teams)\\/([\\w\\.]+).+(electron\\/|; ios)", "(flipboard)\\/([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{ "(evernote) win", "(teams)mobile-(ios|and)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"chatlyio\\/([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Slack" }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"ultralite app_version\\/([\\w\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "TikTok Lite" }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"\\) code\\/([\\d\\.]+).+electron\\/"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "VS Code" }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
    .{
        .patterns = &.{"jp\\.co\\.yahoo\\.(?:android\\.yjtop|ipn\\.appli)\\/([\\d\\.]+)"},
        .props = &.{ .{ .field = .version, .kind = .capture }, .{ .field = .name, .kind = .static, .value = "Yahoo! Japan" }, .{ .field = .type, .kind = .static, .value = "inapp" } },
    },
};

pub const inapps_cpu_rules = [_]Rule{};

pub const inapps_device_rules = [_]Rule{};

pub const inapps_engine_rules = [_]Rule{};

pub const inapps_os_rules = [_]Rule{};

pub const libraries_browser_rules = [_]Rule{
    .{
        .patterns = &.{ "^((?:apache|go|java)-http-?client|axios|bun|dart|deno|got|(?:guzzle|lua-resty-|ocaml-co|ok)http|hackney|http\\.rb|java|jetty|libwww-perl|needle|node(?:\\.js|-fetch|-superagent)|php-soap|postmanruntime|python-(?:httpx|urllib[23]?|requests)|rest-client|scrapy)\\/([\\w\\.]+)", "(adobeair|aiohttp|jsdom)\\/([\\w\\.]+)", "(nutch)-([\\w\\.-]+)(\\(|$)", "\\((java)\\/([\\w\\.]+)" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "library" } },
    },
    .{
        .patterns = &.{"(node-fetch|undici)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "library" } },
    },
};

pub const libraries_cpu_rules = [_]Rule{};

pub const libraries_device_rules = [_]Rule{};

pub const libraries_engine_rules = [_]Rule{};

pub const libraries_os_rules = [_]Rule{};

pub const mediaplayers_browser_rules = [_]Rule{
    .{
        .patterns = &.{ "(apple(?:coremedia|tv))\\/([\\w\\._]+)", "(coremedia) v([\\w\\._]+)", "(ares|clementine|music player daemon|nexplayer|ossproxy) ([\\w\\.-]+)", "^(aqualung|audacious|audimusicstream|amarok|bass|bsplayer|core|gnomemplayer|gvfs|irapp|lyssna|music on console|nero (?:home|scout)|nokia\\d+|nsplayer|psp-internetradioplayer|quicktime|rma|radioapp|radioclientapplication|soundtap|stagefright|streamium|totem|videos|xbmc|xine|xmms)\\/([\\w\\.-]+)", "(lg player|nexplayer) ([\\d\\.]+)", "player\\/(nexplayer|lg player) ([\\w\\.-]+)", "(gstreamer) souphttpsrc.+libsoup\\/([\\w\\.-]+)", "(htc streaming player) [\\w_]+ \\/ ([\\d\\.]+)", "(lavf)([\\d\\.]+)", "(mplayer)(?: |\\/)(?:(?:sherpya-){0,1}svn)(?:-| )(r\\d+(?:-\\d+[\\w\\.-]+))", " (songbird)\\/([\\w\\.-]+)", "(winamp)(?:3 version|mpeg| ) ([\\w\\.-]+)", "(vlc)(?:\\/| media player - version )([\\w\\.-]+)", "^(foobar2000|itunes|smp)\\/([\\d\\.]+)", "com\\.(riseupradioalarm)\\/([\\d\\.]*)", "(mplayer)(?:\\s|\\/| unknown-)([\\w\\.\\-]+)", "(windows)\\/([\\w\\.-]+) upnp\\/[\\d\\.]+ dlnadoc\\/[\\d\\.]+ home media server" },
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mediaplayer" } },
    },
    .{
        .patterns = &.{"(flrp)\\/([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "Flip Player" }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mediaplayer" } },
    },
    .{
        .patterns = &.{"(fstream|media player classic|inlight radio|mplayer|nativehost|nero showtime|ocms-bot|queryseekspider|tapinradio|tunein radio|winamp|yourmuze)"},
        .props = &.{ .{ .field = .name, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mediaplayer" } },
    },
    .{
        .patterns = &.{"(htc_one_s|windows-media-player|wmplayer)\\/([\\w\\.-]+)"},
        .props = &.{ .{ .field = .name, .kind = .replace, .replace = .{
            .pattern = "[_-]",
            .replacement = " ",
            .global = true,
            .caseless = false,
        } }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mediaplayer" } },
    },
    .{
        .patterns = &.{"(rad.io|radio.(?:de|at|fr)) ([\\d\\.]+)"},
        .props = &.{ .{ .field = .name, .kind = .static, .value = "rad.io" }, .{ .field = .version, .kind = .capture }, .{ .field = .type, .kind = .static, .value = "mediaplayer" } },
    },
};

pub const mediaplayers_cpu_rules = [_]Rule{};

pub const mediaplayers_device_rules = [_]Rule{};

pub const mediaplayers_engine_rules = [_]Rule{};

pub const mediaplayers_os_rules = [_]Rule{};

pub const vehicles_browser_rules = [_]Rule{};

pub const vehicles_cpu_rules = [_]Rule{};

pub const vehicles_device_rules = [_]Rule{
    .{
        .patterns = &.{"aftlbt962e2"},
        .props = &.{.{ .field = .vendor, .kind = .static, .value = "BMW" }},
    },
    .{
        .patterns = &.{"dilink.+(byd) auto"},
        .props = &.{.{ .field = .vendor, .kind = .capture }},
    },
    .{
        .patterns = &.{"aftlft962x3"},
        .props = &.{ .{ .field = .vendor, .kind = .static, .value = "Jeep" }, .{ .field = .model, .kind = .static, .value = "Wagooner" } },
    },
    .{
        .patterns = &.{"(rivian) (r1t)"},
        .props = &.{ .{ .field = .vendor, .kind = .capture }, .{ .field = .model, .kind = .capture } },
    },
    .{
        .patterns = &.{"vcc.+netfront"},
        .props = &.{.{ .field = .vendor, .kind = .static, .value = "Volvo" }},
    },
};

pub const vehicles_engine_rules = [_]Rule{};

pub const vehicles_os_rules = [_]Rule{};
